"""
constants.py — Project-wide constants and symbols.
"""

# Common F&O Stocks (Top Nifty 50 + others)
FO_STOCKS = [
    "RELIANCE", "TCS", "HDFCBANK", "ICICIBANK", "INFY", "HINDUNILVR", "ITC", "SBIN", "BHARTIARTL", "BAJFINANCE",
    "LT", "KOTAKBANK", "HCLTECH", "AXISBANK", "ASIANPAINT", "MARUTI", "SUNPHARMA", "TITAN", "ULTRACEMCO", "ADANIENT",
    "TATASTEEL", "NTPC", "M&M", "POWERGRID", "JSWSTEEL", "ADANIPORTS", "HINDALCO", "GRASIM", "COALINDIA", "BAJAJFINSV",
    "TATAMOTORS", "INDUSINDBK", "ONGC", "NESTLEIND", "DRREDDY", "TECHM", "WIPRO", "HDFCLIFE", "SBILIFE", "BPCL",
    "HEROMOTOCO", "EICHERMOT", "BRITANNIA", "CIPLA", "APOLLOHOSP", "DIVISLAB", "BAJAJ-AUTO", "SHREECEM", "UPL", "TATACONSUM"
]

# Indices
INDEX_SYMBOLS = ["NIFTY", "BANKNIFTY", "FINNIFTY", "MIDCPNIFTY"]

# All symbols
ALL_SYMBOLS = FO_STOCKS + INDEX_SYMBOLS
